# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: false
os:
  - linux
  - osx
warnings_are_errors: false

env:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"; fi

after_success:
  - Rscript -e 'covr::codecov()'
